export const PROPERTIES = [
    { id: "friends-monica-2br", name: "Monica Geller’s Rent-Controlled 2BR (Purple Apartment)" },
    { id: "friends-joey-chandler-2br", name: "Joey & Chandler’s Bachelor 2BR (Across the Hall)" },
    { id: "friends-ross-1br", name: "Ross Geller’s Museum-Friendly 1BR" },
    { id: "friends-phoebe-1br", name: "Phoebe Buffay’s Grandmother’s Walk-Up (1BR)" },
    { id: "himym-ted-2br", name: "Ted Mosby’s Upper West Side Walk-Up (2BR)" },
    { id: "himym-marshall-lily-2br", name: "Marshall & Lily’s Pre-Wedding Apartment (2BR)" },
    { id: "himym-barney-1br", name: "Barney Stinson’s Luxury High-Rise (1BR)" },
    { id: "tbbt-apt-4a", name: "Apartment 4A – Sheldon & Leonard’s 2BR" },
    { id: "tbbt-apt-4b", name: "Apartment 4B – Penny’s Studio" },
    { id: "bb-walter-white-house", name: "Walter White Family Home (3BR)" },
    { id: "bb-jesse-house", name: "Jesse Pinkman’s Aunt Ginny’s House (2BR)" },
    { id: "bb-saul-office", name: "Saul Goodman’s Back-Office Studio (Short Stays)" },
    { id: "got-winterfell-guest-wing", name: "Winterfell – Guest Wing (5 Chambers)" },
    { id: "got-winterfell-lords-solar", name: "Winterfell – Lord’s Solar (Private Suite)" },
    { id: "got-red-keep-apartments", name: "King’s Landing – Red Keep Guest Apartments" },
    { id: "downton-east-wing-suite", name: "Downton Abbey – East Wing Guest Suite" },
    { id: "downton-servants-quarters", name: "Downton Abbey – Attic Servants’ Quarters" },
    { id: "hp-gryffindor-dorm", name: "Hogwarts – Gryffindor Tower Dormitory" },
    { id: "hp-slytherin-suite", name: "Hogwarts – Slytherin Dungeon Suite" },
    { id: "hp-hagrids-hut", name: "Hagrid’s Hut – Forest Edge (1BR)" },
    { id: "hp-weasley-burrow", name: "The Burrow – Weasley Family Home (4BR)" },
    { id: "hp-malfoy-manor", name: "Malfoy Manor – East Wing Guest Chambers" },
    { id: "lotr-bag-end", name: "Bag End – Hobbiton Hillside Home (1BR)" },
    { id: "office-dunder-mifflin", name: "Dunder Mifflin – Scranton Office Floor" },
    { id: "parks-leslie-house", name: "Leslie Knope’s Pawnee House (2BR)" },
    { id: "seinfeld-apt", name: "Jerry Seinfeld’s Upper West Side Apartment (1BR)" },
];
